name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

env:
  FORCE_COLOR: 2
  NODE: 14

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE }}"

      - run: java -version

      - name: Set up npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.NODE }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}

      - name: Install npm dependencies
        run: npm ci

      - name: Build docs
        run: npm run build

      - name: Test docs
        run: npm test

      - name: Upload docs
        uses: actions/upload-artifact@v2
        if: success() && github.repository == 'twbs/blog' && github.ref == 'refs/heads/main'
        with:
          name: docs
          path: ./_site/
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.repository == 'twbs/blog' && github.ref == 'refs/heads/main'

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Download docs
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: ./_site/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          allow_empty_commit: false
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site/
